const data = {
    products: [
        {
            name: 'Nike slim shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: 'images/p1.jpg', //679px * 829px
            price: 120,
            countInStock:10,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Adidas slim shirt',
            slug: 'adidas-slim-shirt',
            category: 'Shirts',
            image: 'images/p2.jpg',
            price: 250,
            countInStock:20,
            brand: 'Adidas',
            rating: 4.0,
            numReview: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nike slim pant',
            slug: 'nike-slim-pant',
            category: 'Pants',
            image: 'images/p3.jpg',
            price: 300,
            countInStock:25,
            brand: 'Nike',
            rating: 4.5,
            numReview: 20,
            description: 'high quality pant',
        },
        {
            name: 'Adidas slim pant',
            slug: 'adidas-slim-pant',
            category: 'Pants',
            image: 'images/p4.jpg',
            price: 280,
            countInStock:22,
            brand: 'Adidas',
            rating: 4.5,
            numReview: 10,
            description: 'high quality pant',
        },
    ],
};
export default data;